label game_mid:
    "And then, game begins."
    
    scene chess start
    show susie normal at left
    show david normal at right
    
    "David and Susie seat in front of each other, taking sides of a weird ritual table."
    "On top of normal chess table you can find in any club, there's a black plank, flat on top and slightly curved on bottom."
    "Only on top of it lies chess board."
    "It's not some usual cheap ritualizing stuff like sacrificial plate you can find in other chess clubs."
    "It seems much more ancient and authentic."
    "Even the oldest players which seen it can't say what is that."
    "Some say it's one of the artifacts, but then why nobody could make use of it?"
    "Everybody know now that artifacts are not some kind of abstract magic."
    "Guns are made to kill and wound people and not to dance around and pray."
    "Conserve cans just contain some weird preserved food in them and not supposed to be used as drums."
    "Not to mention lots of more obvious things."
    "But this plank, sometimes referred to as \"eskriin\" (after someone claimed to learn this name from remains of ancient civilization), is different."
    "No one ever imagined reasonable explanation for it."
    "Maybe it's just broken. Or maybe it is the actual ritual stuff bearing no reasonable meaning from the beginning."
    ".."

    "But the game is usually more interesting than what it is played on."
    "First few moves are nothing interesting. Only confirming opponents have some basic openings knowledge."
    
    ".."
    
    "Suddenly when i look at the faces of players, i see David speaking."
    dav "..at brings you here?"
    "I can't hear him in this noise, but some time ago i lost my hearing and then learned to read speech by mouth."
    "Luckily, i sit in position where i can see both of their faces and quite close."
    dav "You don't need to tell if you don't want to, but won't it be more human to at least know your opponent?"
    dav "And if you are in grief, it's better to speak it off to somebody."
    sus ".."
    "Susie still remains silent."
    dav "Ok, i'll start about talking myself first then."
    dav "As you might know, my name's David."
    dav "I was born in a small village far far north."
    dav "So far, that we when there was winter, we rarely saw sun at all."
    dav "It surely was cold as hell, but we all were used to it from childhood."
    dav "But even being born there, i couldn't get used to live nearly half of year in darkness."
    dav "Probably that's because i heard stories and read books about sunny southern lands."
    dav "Otherwise, how could child even imagine that there could be different places?.."
    "Despite talking, David is still playing."
    "There is no strict time control in such games, except for when players demand it."
    "So it's completely fine that his thinking takes some time."
    "But maybe he's doing that to distract opponent?.."
    dav "..And then someday i decided to run away to those great lands of south i created in my imagination."
    dav "I was young and naive and couldn't understand the world isn't like those fancy stories."
    dav "So then my journey started."
    dav "I can call it a miracle that i survived first winter."
    dav "I met it in a city called Eshuima."
    dav "It was way souther than my nameless village, but it wasn't that warm fertile land i imagined."
    dav "Only summer was hot, but the winter was still cold and if i wouldn't find a place to live in, i would die for sure."
    dav "But that place was still hell."
    dav "Not freezing hell i was used to, but hot hell of everyday twelve-hour hard labour."
    dav "If you have never left this city, you probably never saw the great machinery of mid-north people."
    dav "It still comes to me in my nightmares."
    dav "Judging by rumors i heard there, they decided to rebuild empire of their ancestors."
    dav "No, they don't have it yet. They only have several cities and a bunch of villages around them."
    dav "But they are building power."
    dav "They restored a lot of knowledge from the past and keeping it in secret, use it for what they are calling \"industry\"."
    dav "I worked there. I know what it means."
    dav "It's not the path to world prosperity and happiness like some fools think it to be."
    dav "Just take one aspect."
    dav "Here, in this town of darkness and ignorance, you have some guns from ancient era."
    dav "They are being repaired and passed on from generation to generation."
    dav "Ammunition for them is either awful or hard to produce and extremely costly."
    dav "So you don't even use guns for hunting."
    dav "Only for defence except for rare types who.."
    "At this point, i wasn't able to see what he was saying."
    "Someone was in the way of my sight and i could only see big \"magnetic chess\" board, which reproduced the game for those who couldn't see original."
    "This brought me back to reality for a moment."
    "I nearly completely ignored the sounds while i was watching David's speech and now wave of noise filled my ears."
    "And i even stopped to follow the game, which was slowly moving forward."
    "They played open game, getting rid of figures without any reluctance, and now each had only Knight out of light figures."
    "And while she might not realize bad consequences of this, Susie is left with two pairs of doubled pawns."
    "One of my neighbours seem to be irritated by this, spreading irritation further."
    "Trying to ignore him, i glance back at playing table and is captured back into David's monologue."
    dav "..produce everything using conveyor technology, increasing production rate and decreasing price."
    dav "Price of shells is so low that you could hear gunfire all day long in several districts."
    dav "And these are not from armed thugs - no, security is good there because most of society is so maniac about their \"state\"."
    dav "These are from firing ranges where youngsters are trained to shoot."
    "When he said \"shoot\", Susie looked at him and then moved Queen to check his King."
    "He paused briefly, looking at board."
    "Then without much thinking, moved king away."
    dav "So, what was i speaking about?.."
    dav "Enough of this Eshuima talk."
    dav "When the spring came and nights became warm enough to not freeze to death near fire, i run away from there even with more resolution than i had leaving my home."
    dav "I was traveling with trading caravans, by myself, then with a gang of ruffians."
    "Suddenly he stopped. Susie was looking at him with mixed expression of interest and fear."
    dav "..Why.. yet again, because i was so naive."
    "He probably answered her question which i missed."
    dav "I read ancient legends about nice villains."
    dav "But these were different. They weren't some kind of violent blood-thirsty maniacs, no."
    dav "But they only cared about having fun: drinking and gambling while they had money and robbing (and thus occasionally killing) people when they run out of it."
    dav "Probably i was raised in completely different culture, but it seemed strange to me: they were so nice and friendly to me, complete stranger, just because i joined them."
    dav "And with the same easiness they killed or took away last means of living from other strangers who happened to be in their way."
    
    "Then he abruptly stopped talking again, looking at the board."
    "His previous move was made without thinking and Susie used that."
    "Now he had only one possible move and that was loosing Queen without even taking weaker figure in exchange."
    "With a sad smile on his face, he made that move."
    "Susie looks more confident now."
    "Before, she looked so desperate that i couldn't see any glimmer of hope on her face."
    "Now she had that specific expression of people who see their spider thread appearing of nowhere and leading them to salvation."
    "David stopped talking for a while, concentrating on thinking."
    "Public demanded action."
    "Some were in rage for this careless loss."
    "My neighbour mentioned above was happy and was yelling \"GIVE UP, GIVE UP\"."
    "Several fellows picked that up and for a brief moment noise became unbearingly loud."
    "Somehow, stuff managed to calm the crowd down."
    "In the corner of my view i see guards taking away one of the most stubborn disturbers."

    "<<<<>>>>"
    
    "It's turn 28. David doesn't seem to accept his loss yet."
    "After spending some time in aimless rambling, he seems to have created plan."
    "He moves Knight with confidence of a man who has placed all his hope into single chance."
    "Susie thinks for a while, before doing weird pawn move, only provoking David to eat the pawn next turn."
    "The atmosphere gets more nervous."
    "Black has clear material advantage, yet the situation around the King is dangerous."
    "Another turn and it's David checks by opening rooks."
    "Susie again thinks for a while. Then considering possible material loss, she moves King into the corner."
    "Victory smile appears on her opponent's face."
    "He checks again, sacrificing one of rooks."
    "Black are forced to accept sacrifice."
    "And next move, already foreseen by few more professional watchers, is mate with that same Knight."
    ".."
    "Now public roars without any previous hesitation."
    "Those who won and those who lost their bets. And those who were watching for fun."
    "Winner is praised and applaused, looser looses interest of most, while some notorious fellows already approach her to offer their dirty deals."
    
    return
